# Generated by Django 2.2.6 on 2019-11-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalDeviceId', models.CharField(max_length=24, unique=True)),
                ('friendlyName', models.CharField(max_length=24)),
                ('deviceHandlerType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'device_info',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=24)),
                ('capability', models.CharField(max_length=24)),
                ('attribute', models.CharField(max_length=24)),
                ('value', models.CharField(max_length=24)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_oauth.Device')),
            ],
            options={
                'db_table': 'device_states',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturerName', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
                ('hwVersion', models.CharField(blank=True, default='', max_length=50)),
                ('swVersion', models.CharField(blank=True, default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_oauth.Device')),
            ],
            options={
                'db_table': 'device_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(blank=True, default='', max_length=50)),
                ('groups', models.CharField(blank=True, default='', max_length=50)),
                ('categories', models.CharField(blank=True, default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_oauth.Device')),
            ],
            options={
                'db_table': 'device_context',
            },
        ),
    ]
